CREATE DATABASE IF NOT EXISTS logger_db;
CREATE USER 'loguser'@'%' IDENTIFIED BY 'loguserpass!';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `logger_db`.* TO 'loguser'@'%';
FLUSH PRIVILEGES;